# Generated by Django 4.1.5 on 2023-01-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
