# Generated by Django 4.1.5 on 2023-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_name_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
